---
name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  perlcritic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perlcritic
        uses: Difegue/action-perlcritic@master
        with:
          args: nix-update-cpan.pl
